source 'https://rubygems.org'
group :jekyll_plugins do
  gem 'jekyll', '4.2.2'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed', '0.16.0'
    gem 'jekyll-imagemagick'
    gem 'jekyll-minifier'
    gem 'jekyll-polyglot', '1.5.0'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar', '7.1.0'
    gem 'jekyll-seo-tag'
    gem 'jekyll-sitemap', :git => 'https://github.com/shota-horiguchi/jekyll-sitemap.git'
    gem 'jekyll-target-blank'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji', '0.12.0'
    gem 'mini_racer'
    gem 'unicode_utils'
    gem 'webrick'
end
group :other_plugins do
    gem 'httparty'
    gem 'feedjira'
end
